# Generated by Django 3.0.7 on 2020-06-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LP_name', models.CharField(max_length=100)),
                ('LP_img', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
