# Generated by Django 3.0.7 on 2020-06-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20200610_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='edit',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
